service: uc8-frontend
app: uc8
org: psrandapps

plugins:
  - serverless-finch
  - serverless-python-requirements

deploymentBucket:
  name: uc8-frontend-deployment-artifacts

custom:
  client:
    bucketName: uc8-frontend-psrandapps
    bucketPrefix: frontend/
    # Uncomment and set if you want to use a custom domain
    distributionFolder: dist
    indexDocument: index.html
    errorDocument: index.html
    region: us-east-1
  pythonRequirements:
    dockerizePip: true
    # Uncomment and set if you want to use a custom domain
    # domain: your.custom.domain.com

provider:
  name: aws
  region: us-east-1