# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: psrandapps
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: uc8
service: fastapi-backend

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 30

functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - tests/**
    - frontend/**
    - .venv/**
    - .git/**
    - '*.md'
    - '*.log'